### ISSUE TITLE
@mojodna modules

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapnik-swoop#1]
Hey @mojodna. This repo is designed to help me test - in one fell swoop - all the modules that depend on node-mapnik to help avoid accidental breakages or alert me of other issues before release.

The idea is that the mapnik-swoop .travis.yml will download all dependents, ensure no duplicate node-mapnik versions got installed, and then run each modules' tests. You've got a bunch of tilelive-* modules on npm: want to recommend which ones would be good to include here?

**Comment by springmeyer** [comment]
Okay, I've added those and yes: we hit duplicate module errors for both `node-mapnik` and `node-sqlite3`:

```
mapnik-swoop@0.1.0 /home/travis/build/mapbox/mapnik-swoop
├── mapnik@3.1.3 
├─┬ tilelive-solid@0.1.0
│ └── mapnik@1.4.17 
└─┬ tilelive-tmsource@0.1.2
  └── mapnik@1.4.17 
```

and

```
mapnik-swoop@0.1.0 /home/travis/build/mapbox/mapnik-swoop
├─┬ carmen@1.5.2
│ └─┬ mbtiles@0.7.7
│   └── sqlite3@3.0.4 
├── sqlite3@3.0.4 
└─┬ tilelive@5.5.2
  └─┬ mbtiles@0.7.7
    └── sqlite3@3.0.4 
```

@mojodna - would it be possible for you to modify your modules to accept node-mapnik 3.x as well as 1.x?

**Comment by mojodna** [comment]
Yup, definitely.

**Comment by mojodna** [comment]
Done in tilelive-solid@0.1.1 and tilelive-tmsource@0.1.3

**Comment by springmeyer** [comment]
@mojodna thanks! Can you also upgrade tilelive-bridge in tilelive-tmsource? I assume that will fix this error that persists in the mapnik-swoop travis run:

```
├── mapnik@3.1.3 
└─┬ tilelive-tmsource@0.1.3
  └─┬ tilelive-bridge@0.4.0
    └── mapnik@1.4.17 
```

**Comment by mojodna** [comment]
Sure, will do.

**Comment by springmeyer** [comment]
Thanks! Added you as a collaborator so you can, if you wish, either restart the travis build or commit to trigger a new build to test the fix.

**Comment by mojodna** [comment]
```
ERROR: Permission to mapbox/mapnik-swoop.git denied to mojodna.
```

I realized `tilelive-xray` was missing, so I'll send a PR your way momentarily.

Incidentally, the cleanest way I've found to fix this is to declare a `peerDependency` on `mapnik` `>=1.4.9` (or whatever), which will force it to use (and potentially conflict with on install) a version outside a module's own `node_modules/`.  `tilelive-bridge` and `tilelive-vector` would probably benefit from this.

**Comment by springmeyer** [comment]
> ERROR: Permission to mapbox/mapnik-swoop.git denied to mojodna.

Sorry, should be working now.

> I realized tilelive-xray was missing, so I'll send a PR your way momentarily.


Thanks, merged. but the `mojodna` branch is still failing as it appears the `peerDependency` fix is not working?

**Comment by springmeyer** [comment]
not going to try to fix this, closing.

**Comment by mojodna** [comment]
Bah.  Fine.

:grin:

**Comment by springmeyer** [comment]
> Bah. Fine.

Haha. Basically I don't use or understand `peerDependency`, but if you can advise on what I'm doing wrong, let me know.

**Comment by mojodna** [comment]
Some day, perhaps. (Also not going to try to fix this in the short-term.) We have an ongoing argument here about how `peerDependency`s work...

Anecdotally I've been hearing about fewer problems, so things are either improving or we're getting better at getting people to ensure that there's only one `mapnik` module present in the tree.
