### ISSUE TITLE
Add raster-tile-query

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapnik-swoop#4]
https://github.com/mapbox/raster-tile-query

/cc @flippmoke @dnomadb

**Comment by mapsam** [comment]
Knocking this out in https://github.com/mapbox/mapnik-swoop/commit/4311bc9021a6454529263c09998fe6229c3863aa

**Comment by springmeyer** [comment]
I've now got master passing. When trying to rebase`new-modules` against master I ran into nasty merge conflicts (I think due to the use of `npm --save` in the `new-modules` branch) so I committed directly: https://github.com/mapbox/mapnik-swoop/commit/83884a27994fe816f1011db721cb7ace069c6868
