### ISSUE TITLE
Add mapbox-upload-validate

### ISSUE THREAD

**Issue by mapsam** [mapbox/mapnik-swoop#8]
Let's add https://github.com/mapbox/mapbox-upload-validate to the swoop!

**Comment by mapsam** [comment]
Added this and tests are passing, but with a weird error:

```
mapbox-upload-validate --> 
ERROR: Can't open test
    ✓ mapbox-upload-validate tests  (699ms)
```

**Comment by springmeyer** [comment]
Hmm, not sure where `ERROR: Can't open test` is coming from. (Checked in mapnik-swoop https://github.com/mapbox/mapnik-swoop/blob/master/test.js and grepped in https://github.com/mapbox/mapbox-upload-validate/tree/master/test)

**Comment by mapsam** [comment]
I think it's a `jshint` error, see https://github.com/jshint/jshint/issues/1405

**Comment by springmeyer** [comment]
Nice find @mapsam. Looks like `jshint` is being run due to the `pretest` entry here: https://github.com/mapbox/mapbox-upload-validate/blob/master/package.json#L7. We really only care about the `test` entry, but I've never been able to find a way to run just the `test` without it also calling the `pretest`.

**Comment by mapsam** [comment]
Oh actually it looks like `mapbox-upload-validate` ignores the `/test` directory when publishing to NPM. 

https://github.com/mapbox/mapbox-upload-validate/blob/master/.npmignore#L1

Maybe @GretaCB has some insight here.

**Comment by springmeyer** [comment]
@mapsam - that is fine - you want to include the module via its github url so the whole thing gets pulled down (rather than using a published version).

**Comment by mapsam** [comment]
Doh, okay right. `test` directory is back and getting real errors instead of fake ones :smile:

**Comment by mapsam** [comment]
New errors:

```
mapbox-upload-validate --> 
not ok 1 you are missing the mapnik module (`npm ls mapnik`)
  ---
    operator: notEqual
    expected: undefined
    actual:   0
  ...
not ok 2 you have more than one copy of mapnik (`npm ls mapnik`)
  ---
    operator: equal
    expected: 1
    actual:   0
  ...
# Duplicate modules: there should only be one tilelive otherwise you are asking for pwnage
```

**Comment by springmeyer** [comment]
I've now got master passing. When trying to rebase`new-modules` against master I ran into nasty merge conflicts (I think due to the use of `npm --save` in the `new-modules` branch) so I committed directly: https://github.com/mapbox/mapnik-swoop/commit/83884a27994fe816f1011db721cb7ace069c6868
